<?php


/**
 * Base class that represents a query for the 'sf_blog_post' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed 26 Jan 2011 10:35:17 PM WIT
 *
 * @method     sfSimpleBlogPostQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     sfSimpleBlogPostQuery orderByAuthorId($order = Criteria::ASC) Order by the author_id column
 * @method     sfSimpleBlogPostQuery orderByTitle($order = Criteria::ASC) Order by the title column
 * @method     sfSimpleBlogPostQuery orderByStrippedTitle($order = Criteria::ASC) Order by the stripped_title column
 * @method     sfSimpleBlogPostQuery orderByContent($order = Criteria::ASC) Order by the content column
 * @method     sfSimpleBlogPostQuery orderByIsPublished($order = Criteria::ASC) Order by the is_published column
 * @method     sfSimpleBlogPostQuery orderByAllowComments($order = Criteria::ASC) Order by the allow_comments column
 * @method     sfSimpleBlogPostQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method     sfSimpleBlogPostQuery orderByPublishedAt($order = Criteria::ASC) Order by the published_at column
 * @method     sfSimpleBlogPostQuery orderByInternalPublishedAt($order = Criteria::ASC) Order by the internal_published_at column
 * @method     sfSimpleBlogPostQuery orderByVersion($order = Criteria::ASC) Order by the version column
 *
 * @method     sfSimpleBlogPostQuery groupById() Group by the id column
 * @method     sfSimpleBlogPostQuery groupByAuthorId() Group by the author_id column
 * @method     sfSimpleBlogPostQuery groupByTitle() Group by the title column
 * @method     sfSimpleBlogPostQuery groupByStrippedTitle() Group by the stripped_title column
 * @method     sfSimpleBlogPostQuery groupByContent() Group by the content column
 * @method     sfSimpleBlogPostQuery groupByIsPublished() Group by the is_published column
 * @method     sfSimpleBlogPostQuery groupByAllowComments() Group by the allow_comments column
 * @method     sfSimpleBlogPostQuery groupByUpdatedAt() Group by the updated_at column
 * @method     sfSimpleBlogPostQuery groupByPublishedAt() Group by the published_at column
 * @method     sfSimpleBlogPostQuery groupByInternalPublishedAt() Group by the internal_published_at column
 * @method     sfSimpleBlogPostQuery groupByVersion() Group by the version column
 *
 * @method     sfSimpleBlogPostQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     sfSimpleBlogPostQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     sfSimpleBlogPostQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     sfSimpleBlogPostQuery leftJoinsfGuardUser($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfGuardUser relation
 * @method     sfSimpleBlogPostQuery rightJoinsfGuardUser($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfGuardUser relation
 * @method     sfSimpleBlogPostQuery innerJoinsfGuardUser($relationAlias = null) Adds a INNER JOIN clause to the query using the sfGuardUser relation
 *
 * @method     sfSimpleBlogPostQuery leftJoinsfSimpleBlogPostCategory($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfSimpleBlogPostCategory relation
 * @method     sfSimpleBlogPostQuery rightJoinsfSimpleBlogPostCategory($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfSimpleBlogPostCategory relation
 * @method     sfSimpleBlogPostQuery innerJoinsfSimpleBlogPostCategory($relationAlias = null) Adds a INNER JOIN clause to the query using the sfSimpleBlogPostCategory relation
 *
 * @method     sfSimpleBlogPostQuery leftJoinsfSimpleBlogPostVersion($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfSimpleBlogPostVersion relation
 * @method     sfSimpleBlogPostQuery rightJoinsfSimpleBlogPostVersion($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfSimpleBlogPostVersion relation
 * @method     sfSimpleBlogPostQuery innerJoinsfSimpleBlogPostVersion($relationAlias = null) Adds a INNER JOIN clause to the query using the sfSimpleBlogPostVersion relation
 *
 * @method     sfSimpleBlogPost findOne(PropelPDO $con = null) Return the first sfSimpleBlogPost matching the query
 * @method     sfSimpleBlogPost findOneOrCreate(PropelPDO $con = null) Return the first sfSimpleBlogPost matching the query, or a new sfSimpleBlogPost object populated from the query conditions when no match is found
 *
 * @method     sfSimpleBlogPost findOneById(int $id) Return the first sfSimpleBlogPost filtered by the id column
 * @method     sfSimpleBlogPost findOneByAuthorId(int $author_id) Return the first sfSimpleBlogPost filtered by the author_id column
 * @method     sfSimpleBlogPost findOneByTitle(string $title) Return the first sfSimpleBlogPost filtered by the title column
 * @method     sfSimpleBlogPost findOneByStrippedTitle(string $stripped_title) Return the first sfSimpleBlogPost filtered by the stripped_title column
 * @method     sfSimpleBlogPost findOneByContent(string $content) Return the first sfSimpleBlogPost filtered by the content column
 * @method     sfSimpleBlogPost findOneByIsPublished(boolean $is_published) Return the first sfSimpleBlogPost filtered by the is_published column
 * @method     sfSimpleBlogPost findOneByAllowComments(boolean $allow_comments) Return the first sfSimpleBlogPost filtered by the allow_comments column
 * @method     sfSimpleBlogPost findOneByUpdatedAt(string $updated_at) Return the first sfSimpleBlogPost filtered by the updated_at column
 * @method     sfSimpleBlogPost findOneByPublishedAt(string $published_at) Return the first sfSimpleBlogPost filtered by the published_at column
 * @method     sfSimpleBlogPost findOneByInternalPublishedAt(string $internal_published_at) Return the first sfSimpleBlogPost filtered by the internal_published_at column
 * @method     sfSimpleBlogPost findOneByVersion(int $version) Return the first sfSimpleBlogPost filtered by the version column
 *
 * @method     array findById(int $id) Return sfSimpleBlogPost objects filtered by the id column
 * @method     array findByAuthorId(int $author_id) Return sfSimpleBlogPost objects filtered by the author_id column
 * @method     array findByTitle(string $title) Return sfSimpleBlogPost objects filtered by the title column
 * @method     array findByStrippedTitle(string $stripped_title) Return sfSimpleBlogPost objects filtered by the stripped_title column
 * @method     array findByContent(string $content) Return sfSimpleBlogPost objects filtered by the content column
 * @method     array findByIsPublished(boolean $is_published) Return sfSimpleBlogPost objects filtered by the is_published column
 * @method     array findByAllowComments(boolean $allow_comments) Return sfSimpleBlogPost objects filtered by the allow_comments column
 * @method     array findByUpdatedAt(string $updated_at) Return sfSimpleBlogPost objects filtered by the updated_at column
 * @method     array findByPublishedAt(string $published_at) Return sfSimpleBlogPost objects filtered by the published_at column
 * @method     array findByInternalPublishedAt(string $internal_published_at) Return sfSimpleBlogPost objects filtered by the internal_published_at column
 * @method     array findByVersion(int $version) Return sfSimpleBlogPost objects filtered by the version column
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model.om
 */
abstract class BasesfSimpleBlogPostQuery extends ModelCriteria
{

	// query_cache behavior
	protected $queryKey = '';

	/**
	 * Initializes internal state of BasesfSimpleBlogPostQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'sfSimpleBlogPost', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new sfSimpleBlogPostQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    sfSimpleBlogPostQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof sfSimpleBlogPostQuery) {
			return $criteria;
		}
		$query = new sfSimpleBlogPostQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    sfSimpleBlogPost|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = sfSimpleBlogPostPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(sfSimpleBlogPostPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(sfSimpleBlogPostPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the author_id column
	 * 
	 * @param     int|array $authorId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByAuthorId($authorId = null, $comparison = null)
	{
		if (is_array($authorId)) {
			$useMinMax = false;
			if (isset($authorId['min'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::AUTHOR_ID, $authorId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($authorId['max'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::AUTHOR_ID, $authorId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::AUTHOR_ID, $authorId, $comparison);
	}

	/**
	 * Filter the query on the title column
	 * 
	 * @param     string $title The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByTitle($title = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($title)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $title)) {
				$title = str_replace('*', '%', $title);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::TITLE, $title, $comparison);
	}

	/**
	 * Filter the query on the stripped_title column
	 * 
	 * @param     string $strippedTitle The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByStrippedTitle($strippedTitle = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($strippedTitle)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $strippedTitle)) {
				$strippedTitle = str_replace('*', '%', $strippedTitle);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::STRIPPED_TITLE, $strippedTitle, $comparison);
	}

	/**
	 * Filter the query on the content column
	 * 
	 * @param     string $content The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByContent($content = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($content)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $content)) {
				$content = str_replace('*', '%', $content);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::CONTENT, $content, $comparison);
	}

	/**
	 * Filter the query on the is_published column
	 * 
	 * @param     boolean|string $isPublished The value to use as filter.
	 *            Accepts strings ('false', 'off', '-', 'no', 'n', and '0' are false, the rest is true)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByIsPublished($isPublished = null, $comparison = null)
	{
		if (is_string($isPublished)) {
			$is_published = in_array(strtolower($isPublished), array('false', 'off', '-', 'no', 'n', '0')) ? false : true;
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::IS_PUBLISHED, $isPublished, $comparison);
	}

	/**
	 * Filter the query on the allow_comments column
	 * 
	 * @param     boolean|string $allowComments The value to use as filter.
	 *            Accepts strings ('false', 'off', '-', 'no', 'n', and '0' are false, the rest is true)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByAllowComments($allowComments = null, $comparison = null)
	{
		if (is_string($allowComments)) {
			$allow_comments = in_array(strtolower($allowComments), array('false', 'off', '-', 'no', 'n', '0')) ? false : true;
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::ALLOW_COMMENTS, $allowComments, $comparison);
	}

	/**
	 * Filter the query on the updated_at column
	 * 
	 * @param     string|array $updatedAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByUpdatedAt($updatedAt = null, $comparison = null)
	{
		if (is_array($updatedAt)) {
			$useMinMax = false;
			if (isset($updatedAt['min'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($updatedAt['max'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::UPDATED_AT, $updatedAt, $comparison);
	}

	/**
	 * Filter the query on the published_at column
	 * 
	 * @param     string|array $publishedAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByPublishedAt($publishedAt = null, $comparison = null)
	{
		if (is_array($publishedAt)) {
			$useMinMax = false;
			if (isset($publishedAt['min'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::PUBLISHED_AT, $publishedAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($publishedAt['max'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::PUBLISHED_AT, $publishedAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::PUBLISHED_AT, $publishedAt, $comparison);
	}

	/**
	 * Filter the query on the internal_published_at column
	 * 
	 * @param     string|array $internalPublishedAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByInternalPublishedAt($internalPublishedAt = null, $comparison = null)
	{
		if (is_array($internalPublishedAt)) {
			$useMinMax = false;
			if (isset($internalPublishedAt['min'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::INTERNAL_PUBLISHED_AT, $internalPublishedAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($internalPublishedAt['max'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::INTERNAL_PUBLISHED_AT, $internalPublishedAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::INTERNAL_PUBLISHED_AT, $internalPublishedAt, $comparison);
	}

	/**
	 * Filter the query on the version column
	 * 
	 * @param     int|array $version The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterByVersion($version = null, $comparison = null)
	{
		if (is_array($version)) {
			$useMinMax = false;
			if (isset($version['min'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::VERSION, $version['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($version['max'])) {
				$this->addUsingAlias(sfSimpleBlogPostPeer::VERSION, $version['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogPostPeer::VERSION, $version, $comparison);
	}

	/**
	 * Filter the query by a related sfGuardUser object
	 *
	 * @param     sfGuardUser|PropelCollection $sfGuardUser The related object(s) to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterBysfGuardUser($sfGuardUser, $comparison = null)
	{
		if ($sfGuardUser instanceof sfGuardUser) {
			return $this
				->addUsingAlias(sfSimpleBlogPostPeer::AUTHOR_ID, $sfGuardUser->getId(), $comparison);
		} elseif ($sfGuardUser instanceof PropelCollection) {
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
			return $this
				->addUsingAlias(sfSimpleBlogPostPeer::AUTHOR_ID, $sfGuardUser->toKeyValue('PrimaryKey', 'Id'), $comparison);
		} else {
			throw new PropelException('filterBysfGuardUser() only accepts arguments of type sfGuardUser or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the sfGuardUser relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function joinsfGuardUser($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfGuardUser');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfGuardUser');
		}
		
		return $this;
	}

	/**
	 * Use the sfGuardUser relation sfGuardUser object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfGuardUserQuery A secondary query class using the current class as primary query
	 */
	public function usesfGuardUserQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfGuardUser($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfGuardUser', 'sfGuardUserQuery');
	}

	/**
	 * Filter the query by a related sfSimpleBlogPostCategory object
	 *
	 * @param     sfSimpleBlogPostCategory $sfSimpleBlogPostCategory  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterBysfSimpleBlogPostCategory($sfSimpleBlogPostCategory, $comparison = null)
	{
		if ($sfSimpleBlogPostCategory instanceof sfSimpleBlogPostCategory) {
			return $this
				->addUsingAlias(sfSimpleBlogPostPeer::ID, $sfSimpleBlogPostCategory->getSfBlogPostId(), $comparison);
		} elseif ($sfSimpleBlogPostCategory instanceof PropelCollection) {
			return $this
				->usesfSimpleBlogPostCategoryQuery()
					->filterByPrimaryKeys($sfSimpleBlogPostCategory->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterBysfSimpleBlogPostCategory() only accepts arguments of type sfSimpleBlogPostCategory or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the sfSimpleBlogPostCategory relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function joinsfSimpleBlogPostCategory($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfSimpleBlogPostCategory');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfSimpleBlogPostCategory');
		}
		
		return $this;
	}

	/**
	 * Use the sfSimpleBlogPostCategory relation sfSimpleBlogPostCategory object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfSimpleBlogPostCategoryQuery A secondary query class using the current class as primary query
	 */
	public function usesfSimpleBlogPostCategoryQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfSimpleBlogPostCategory($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfSimpleBlogPostCategory', 'sfSimpleBlogPostCategoryQuery');
	}

	/**
	 * Filter the query by a related sfSimpleBlogPostVersion object
	 *
	 * @param     sfSimpleBlogPostVersion $sfSimpleBlogPostVersion  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterBysfSimpleBlogPostVersion($sfSimpleBlogPostVersion, $comparison = null)
	{
		if ($sfSimpleBlogPostVersion instanceof sfSimpleBlogPostVersion) {
			return $this
				->addUsingAlias(sfSimpleBlogPostPeer::ID, $sfSimpleBlogPostVersion->getId(), $comparison);
		} elseif ($sfSimpleBlogPostVersion instanceof PropelCollection) {
			return $this
				->usesfSimpleBlogPostVersionQuery()
					->filterByPrimaryKeys($sfSimpleBlogPostVersion->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterBysfSimpleBlogPostVersion() only accepts arguments of type sfSimpleBlogPostVersion or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the sfSimpleBlogPostVersion relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function joinsfSimpleBlogPostVersion($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfSimpleBlogPostVersion');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfSimpleBlogPostVersion');
		}
		
		return $this;
	}

	/**
	 * Use the sfSimpleBlogPostVersion relation sfSimpleBlogPostVersion object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfSimpleBlogPostVersionQuery A secondary query class using the current class as primary query
	 */
	public function usesfSimpleBlogPostVersionQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfSimpleBlogPostVersion($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfSimpleBlogPostVersion', 'sfSimpleBlogPostVersionQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     sfSimpleBlogPost $sfSimpleBlogPost Object to remove from the list of results
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function prune($sfSimpleBlogPost = null)
	{
		if ($sfSimpleBlogPost) {
			$this->addUsingAlias(sfSimpleBlogPostPeer::ID, $sfSimpleBlogPost->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

	// sluggable behavior
	
	/**
	 * Filter the query on the slug column
	 * 
	 * @param     string $slug The value to use as filter.
	 *
	 * @return    sfSimpleBlogPostQuery The current query, for fluid interface
	 */
	public function filterBySlug($slug)
	{
		return $this->addUsingAlias(sfSimpleBlogPostPeer::STRIPPED_TITLE, $slug, Criteria::EQUAL);
	}
	
	/**
	 * Find one object based on its slug
	 * 
	 * @param     string $slug The value to use as filter.
	 * @param     PropelPDO $con The optional connection object
	 *
	 * @return    sfSimpleBlogPost the result, formatted by the current formatter
	 */
	public function findOneBySlug($slug, $con = null)
	{
		return $this->filterBySlug($slug)->findOne($con);
	}

	// versionable behavior
	
	// query_cache behavior
	
	public function setQueryKey($key)
	{
		$this->queryKey = $key;
		return $this;
	}
	
	public function getQueryKey()
	{
		return $this->queryKey;
	}
	
	public function cacheContains($key)
	{
		return apc_fetch($key);
	}
	
	public function cacheFetch($key)
	{
		return apc_fetch($key);
	}
	
	public function cacheStore($key, $value, $lifetime = 3600)
	{
		apc_store($key, $value, $lifetime);
	}
	
	protected function getSelectStatement($con = null)
	{
		$dbMap = Propel::getDatabaseMap(sfSimpleBlogPostPeer::DATABASE_NAME);
		$db = Propel::getDB(sfSimpleBlogPostPeer::DATABASE_NAME);
	  if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		
		if (!$this->hasSelectClause()) {
			$this->addSelfSelectColumns();
		}
	
	  $this->configureSelectColumns();
	  
		$con->beginTransaction();
		try {
			$this->basePreSelect($con);
			$key = $this->getQueryKey();
			if ($key && $this->cacheContains($key)) {
				$params = $this->getParams();
				$sql = $this->cacheFetch($key);
			} else {
				$params = array();
				$sql = BasePeer::createSelectSql($this, $params);
				if ($key) {
					$this->cacheStore($key, $sql);
				}
			}
			$stmt = $con->prepare($sql);
			$db->bindValues($stmt, $params, $dbMap);
			$stmt->execute();
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
		
		return $stmt;
	}
	
	protected function getCountStatement($con = null)
	{
		$dbMap = Propel::getDatabaseMap($this->getDbName());
		$db = Propel::getDB($this->getDbName());
	  if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
	
		$con->beginTransaction();
		try {
			$this->basePreSelect($con);
			$key = $this->getQueryKey();
			if ($key && $this->cacheContains($key)) {
				$params = $this->getParams();
				$sql = $this->cacheFetch($key);
			} else {
				if (!$this->hasSelectClause() && !$this->getPrimaryCriteria()) {
					$this->addSelfSelectColumns();
				}
				$params = array();
				$needsComplexCount = $this->getGroupByColumns()
					|| $this->getOffset()
					|| $this->getLimit()
					|| $this->getHaving()
					|| in_array(Criteria::DISTINCT, $this->getSelectModifiers());
				if ($needsComplexCount) {
					if (BasePeer::needsSelectAliases($this)) {
						if ($this->getHaving()) {
							throw new PropelException('Propel cannot create a COUNT query when using HAVING and  duplicate column names in the SELECT part');
						}
						$db->turnSelectColumnsToAliases($this);
					}
					$selectSql = BasePeer::createSelectSql($this, $params);
					$sql = 'SELECT COUNT(*) FROM (' . $selectSql . ') propelmatch4cnt';
				} else {
					// Replace SELECT columns with COUNT(*)
					$this->clearSelectColumns()->addSelectColumn('COUNT(*)');
					$sql = BasePeer::createSelectSql($this, $params);
				}
				if ($key) {
					$this->cacheStore($key, $sql);
				}
			}
			$stmt = $con->prepare($sql);
			$db->bindValues($stmt, $params, $dbMap);
			$stmt->execute();
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	
		return $stmt;
	}

} // BasesfSimpleBlogPostQuery
