<?php


/**
 * Base static class for performing query and update operations on the 'sf_blog_post_version' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed 26 Jan 2011 10:35:17 PM WIT
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model.om
 */
abstract class BasesfSimpleBlogPostVersionPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'sf_blog_post_version';

	/** the related Propel class for this table */
	const OM_CLASS = 'sfSimpleBlogPostVersion';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'plugins.sfSimpleBlog15Plugin.lib.model.sfSimpleBlogPostVersion';

	/** the related TableMap class for this table */
	const TM_CLASS = 'sfSimpleBlogPostVersionTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 11;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 1;

	/** the column name for the ID field */
	const ID = 'sf_blog_post_version.ID';

	/** the column name for the AUTHOR_ID field */
	const AUTHOR_ID = 'sf_blog_post_version.AUTHOR_ID';

	/** the column name for the TITLE field */
	const TITLE = 'sf_blog_post_version.TITLE';

	/** the column name for the STRIPPED_TITLE field */
	const STRIPPED_TITLE = 'sf_blog_post_version.STRIPPED_TITLE';

	/** the column name for the CONTENT field */
	const CONTENT = 'sf_blog_post_version.CONTENT';

	/** the column name for the IS_PUBLISHED field */
	const IS_PUBLISHED = 'sf_blog_post_version.IS_PUBLISHED';

	/** the column name for the ALLOW_COMMENTS field */
	const ALLOW_COMMENTS = 'sf_blog_post_version.ALLOW_COMMENTS';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'sf_blog_post_version.UPDATED_AT';

	/** the column name for the PUBLISHED_AT field */
	const PUBLISHED_AT = 'sf_blog_post_version.PUBLISHED_AT';

	/** the column name for the INTERNAL_PUBLISHED_AT field */
	const INTERNAL_PUBLISHED_AT = 'sf_blog_post_version.INTERNAL_PUBLISHED_AT';

	/** the column name for the VERSION field */
	const VERSION = 'sf_blog_post_version.VERSION';

	/** The default string format for model objects of the related table **/
	const DEFAULT_STRING_FORMAT = 'YAML';
	
	/**
	 * An identiy map to hold any loaded instances of sfSimpleBlogPostVersion objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array sfSimpleBlogPostVersion[]
	 */
	public static $instances = array();


	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'AuthorId', 'Title', 'StrippedTitle', 'Content', 'IsPublished', 'AllowComments', 'UpdatedAt', 'PublishedAt', 'InternalPublishedAt', 'Version', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'authorId', 'title', 'strippedTitle', 'content', 'isPublished', 'allowComments', 'updatedAt', 'publishedAt', 'internalPublishedAt', 'version', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::AUTHOR_ID, self::TITLE, self::STRIPPED_TITLE, self::CONTENT, self::IS_PUBLISHED, self::ALLOW_COMMENTS, self::UPDATED_AT, self::PUBLISHED_AT, self::INTERNAL_PUBLISHED_AT, self::VERSION, ),
		BasePeer::TYPE_RAW_COLNAME => array ('ID', 'AUTHOR_ID', 'TITLE', 'STRIPPED_TITLE', 'CONTENT', 'IS_PUBLISHED', 'ALLOW_COMMENTS', 'UPDATED_AT', 'PUBLISHED_AT', 'INTERNAL_PUBLISHED_AT', 'VERSION', ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'author_id', 'title', 'stripped_title', 'content', 'is_published', 'allow_comments', 'updated_at', 'published_at', 'internal_published_at', 'version', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'AuthorId' => 1, 'Title' => 2, 'StrippedTitle' => 3, 'Content' => 4, 'IsPublished' => 5, 'AllowComments' => 6, 'UpdatedAt' => 7, 'PublishedAt' => 8, 'InternalPublishedAt' => 9, 'Version' => 10, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'authorId' => 1, 'title' => 2, 'strippedTitle' => 3, 'content' => 4, 'isPublished' => 5, 'allowComments' => 6, 'updatedAt' => 7, 'publishedAt' => 8, 'internalPublishedAt' => 9, 'version' => 10, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::AUTHOR_ID => 1, self::TITLE => 2, self::STRIPPED_TITLE => 3, self::CONTENT => 4, self::IS_PUBLISHED => 5, self::ALLOW_COMMENTS => 6, self::UPDATED_AT => 7, self::PUBLISHED_AT => 8, self::INTERNAL_PUBLISHED_AT => 9, self::VERSION => 10, ),
		BasePeer::TYPE_RAW_COLNAME => array ('ID' => 0, 'AUTHOR_ID' => 1, 'TITLE' => 2, 'STRIPPED_TITLE' => 3, 'CONTENT' => 4, 'IS_PUBLISHED' => 5, 'ALLOW_COMMENTS' => 6, 'UPDATED_AT' => 7, 'PUBLISHED_AT' => 8, 'INTERNAL_PUBLISHED_AT' => 9, 'VERSION' => 10, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'author_id' => 1, 'title' => 2, 'stripped_title' => 3, 'content' => 4, 'is_published' => 5, 'allow_comments' => 6, 'updated_at' => 7, 'published_at' => 8, 'internal_published_at' => 9, 'version' => 10, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. sfSimpleBlogPostVersionPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(sfSimpleBlogPostVersionPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      Criteria $criteria object containing the columns to add.
	 * @param      string   $alias    optional table alias
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria, $alias = null)
	{
		if (null === $alias) {
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::ID);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::AUTHOR_ID);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::TITLE);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::STRIPPED_TITLE);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::CONTENT);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::IS_PUBLISHED);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::ALLOW_COMMENTS);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::PUBLISHED_AT);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::INTERNAL_PUBLISHED_AT);
			$criteria->addSelectColumn(sfSimpleBlogPostVersionPeer::VERSION);
		} else {
			$criteria->addSelectColumn($alias . '.ID');
			$criteria->addSelectColumn($alias . '.AUTHOR_ID');
			$criteria->addSelectColumn($alias . '.TITLE');
			$criteria->addSelectColumn($alias . '.STRIPPED_TITLE');
			$criteria->addSelectColumn($alias . '.CONTENT');
			$criteria->addSelectColumn($alias . '.IS_PUBLISHED');
			$criteria->addSelectColumn($alias . '.ALLOW_COMMENTS');
			$criteria->addSelectColumn($alias . '.PUBLISHED_AT');
			$criteria->addSelectColumn($alias . '.INTERNAL_PUBLISHED_AT');
			$criteria->addSelectColumn($alias . '.VERSION');
		}
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(sfSimpleBlogPostVersionPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			sfSimpleBlogPostVersionPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     sfSimpleBlogPostVersion
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = sfSimpleBlogPostVersionPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return sfSimpleBlogPostVersionPeer::populateObjects(sfSimpleBlogPostVersionPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			sfSimpleBlogPostVersionPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      sfSimpleBlogPostVersion $value A sfSimpleBlogPostVersion object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(sfSimpleBlogPostVersion $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = serialize(array((string) $obj->getId(), (string) $obj->getVersion()));
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A sfSimpleBlogPostVersion object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof sfSimpleBlogPostVersion) {
				$key = serialize(array((string) $value->getId(), (string) $value->getVersion()));
			} elseif (is_array($value) && count($value) === 2) {
				// assume we've been passed a primary key
				$key = serialize(array((string) $value[0], (string) $value[1]));
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or sfSimpleBlogPostVersion object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     sfSimpleBlogPostVersion Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to sf_blog_post_version
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null && $row[$startcol + 9] === null) {
			return null;
		}
		return serialize(array((string) $row[$startcol], (string) $row[$startcol + 9]));
	}

	/**
	 * Retrieves the primary key from the DB resultset row 
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, an array of the primary key columns will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     mixed The primary key of the row
	 */
	public static function getPrimaryKeyFromRow($row, $startcol = 0)
	{
		return array((int) $row[$startcol], (int) $row[$startcol + 9]);
	}
	
	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = sfSimpleBlogPostVersionPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = sfSimpleBlogPostVersionPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = sfSimpleBlogPostVersionPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				sfSimpleBlogPostVersionPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Populates an object of the default type or an object that inherit from the default.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     array (sfSimpleBlogPostVersion object, last column rank)
	 */
	public static function populateObject($row, $startcol = 0)
	{
		$key = sfSimpleBlogPostVersionPeer::getPrimaryKeyHashFromRow($row, $startcol);
		if (null !== ($obj = sfSimpleBlogPostVersionPeer::getInstanceFromPool($key))) {
			// We no longer rehydrate the object, since this can cause data loss.
			// See http://www.propelorm.org/ticket/509
			// $obj->hydrate($row, $startcol, true); // rehydrate
			$col = $startcol + sfSimpleBlogPostVersionPeer::NUM_COLUMNS;
		} else {
			$cls = sfSimpleBlogPostVersionPeer::OM_CLASS;
			$obj = new $cls();
			$col = $obj->hydrate($row, $startcol);
			sfSimpleBlogPostVersionPeer::addInstanceToPool($obj, $key);
		}
		return array($obj, $col);
	}

	/**
	 * Returns the number of rows matching criteria, joining the related sfSimpleBlogPost table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinsfSimpleBlogPost(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(sfSimpleBlogPostVersionPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			sfSimpleBlogPostVersionPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(sfSimpleBlogPostVersionPeer::ID, sfSimpleBlogPostPeer::ID, $join_behavior);

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of sfSimpleBlogPostVersion objects pre-filled with their sfSimpleBlogPost objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of sfSimpleBlogPostVersion objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinsfSimpleBlogPost(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		sfSimpleBlogPostVersionPeer::addSelectColumns($criteria);
		$startcol = (sfSimpleBlogPostVersionPeer::NUM_COLUMNS - sfSimpleBlogPostVersionPeer::NUM_LAZY_LOAD_COLUMNS);
		sfSimpleBlogPostPeer::addSelectColumns($criteria);

		$criteria->addJoin(sfSimpleBlogPostVersionPeer::ID, sfSimpleBlogPostPeer::ID, $join_behavior);

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = sfSimpleBlogPostVersionPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = sfSimpleBlogPostVersionPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = sfSimpleBlogPostVersionPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				sfSimpleBlogPostVersionPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = sfSimpleBlogPostPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = sfSimpleBlogPostPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = sfSimpleBlogPostPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					sfSimpleBlogPostPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (sfSimpleBlogPostVersion) to $obj2 (sfSimpleBlogPost)
				$obj2->addsfSimpleBlogPostVersion($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(sfSimpleBlogPostVersionPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			sfSimpleBlogPostVersionPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(sfSimpleBlogPostVersionPeer::ID, sfSimpleBlogPostPeer::ID, $join_behavior);

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of sfSimpleBlogPostVersion objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of sfSimpleBlogPostVersion objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		sfSimpleBlogPostVersionPeer::addSelectColumns($criteria);
		$startcol2 = (sfSimpleBlogPostVersionPeer::NUM_COLUMNS - sfSimpleBlogPostVersionPeer::NUM_LAZY_LOAD_COLUMNS);

		sfSimpleBlogPostPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (sfSimpleBlogPostPeer::NUM_COLUMNS - sfSimpleBlogPostPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(sfSimpleBlogPostVersionPeer::ID, sfSimpleBlogPostPeer::ID, $join_behavior);

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = sfSimpleBlogPostVersionPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = sfSimpleBlogPostVersionPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = sfSimpleBlogPostVersionPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				sfSimpleBlogPostVersionPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined sfSimpleBlogPost rows

			$key2 = sfSimpleBlogPostPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = sfSimpleBlogPostPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = sfSimpleBlogPostPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					sfSimpleBlogPostPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (sfSimpleBlogPostVersion) to the collection in $obj2 (sfSimpleBlogPost)
				$obj2->addsfSimpleBlogPostVersion($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BasesfSimpleBlogPostVersionPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BasesfSimpleBlogPostVersionPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new sfSimpleBlogPostVersionTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean $withPrefix Whether or not to return the path with the class name
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? sfSimpleBlogPostVersionPeer::CLASS_DEFAULT : sfSimpleBlogPostVersionPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a sfSimpleBlogPostVersion or Criteria object.
	 *
	 * @param      mixed $values Criteria or sfSimpleBlogPostVersion object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from sfSimpleBlogPostVersion object
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a sfSimpleBlogPostVersion or Criteria object.
	 *
	 * @param      mixed $values Criteria or sfSimpleBlogPostVersion object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(sfSimpleBlogPostVersionPeer::ID);
			$value = $criteria->remove(sfSimpleBlogPostVersionPeer::ID);
			if ($value) {
				$selectCriteria->add(sfSimpleBlogPostVersionPeer::ID, $value, $comparison);
			} else {
				$selectCriteria->setPrimaryTableName(sfSimpleBlogPostVersionPeer::TABLE_NAME);
			}

			$comparison = $criteria->getComparison(sfSimpleBlogPostVersionPeer::VERSION);
			$value = $criteria->remove(sfSimpleBlogPostVersionPeer::VERSION);
			if ($value) {
				$selectCriteria->add(sfSimpleBlogPostVersionPeer::VERSION, $value, $comparison);
			} else {
				$selectCriteria->setPrimaryTableName(sfSimpleBlogPostVersionPeer::TABLE_NAME);
			}

		} else { // $values is sfSimpleBlogPostVersion object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		return BasePeer::doUpdate($selectCriteria, $criteria, $con);
	}

	/**
	 * Method to DELETE all rows from the sf_blog_post_version table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(sfSimpleBlogPostVersionPeer::TABLE_NAME, $con, sfSimpleBlogPostVersionPeer::DATABASE_NAME);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			sfSimpleBlogPostVersionPeer::clearInstancePool();
			sfSimpleBlogPostVersionPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a sfSimpleBlogPostVersion or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or sfSimpleBlogPostVersion object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			sfSimpleBlogPostVersionPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof sfSimpleBlogPostVersion) { // it's a model object
			// invalidate the cache for this single object
			sfSimpleBlogPostVersionPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			// primary key is composite; we therefore, expect
			// the primary key passed to be an array of pkey values
			if (count($values) == count($values, COUNT_RECURSIVE)) {
				// array is not multi-dimensional
				$values = array($values);
			}
			foreach ($values as $value) {
				$criterion = $criteria->getNewCriterion(sfSimpleBlogPostVersionPeer::ID, $value[0]);
				$criterion->addAnd($criteria->getNewCriterion(sfSimpleBlogPostVersionPeer::VERSION, $value[1]));
				$criteria->addOr($criterion);
				// we can invalidate the cache for this single PK
				sfSimpleBlogPostVersionPeer::removeInstanceFromPool($value);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			sfSimpleBlogPostVersionPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given sfSimpleBlogPostVersion object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      sfSimpleBlogPostVersion $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(sfSimpleBlogPostVersion $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(sfSimpleBlogPostVersionPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(sfSimpleBlogPostVersionPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(sfSimpleBlogPostVersionPeer::DATABASE_NAME, sfSimpleBlogPostVersionPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve object using using composite pkey values.
	 * @param      int $id
	 * @param      int $version
	 * @param      PropelPDO $con
	 * @return     sfSimpleBlogPostVersion
	 */
	public static function retrieveByPK($id, $version, PropelPDO $con = null) {
		$_instancePoolKey = serialize(array((string) $id, (string) $version));
 		if (null !== ($obj = sfSimpleBlogPostVersionPeer::getInstanceFromPool($_instancePoolKey))) {
 			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogPostVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$criteria = new Criteria(sfSimpleBlogPostVersionPeer::DATABASE_NAME);
		$criteria->add(sfSimpleBlogPostVersionPeer::ID, $id);
		$criteria->add(sfSimpleBlogPostVersionPeer::VERSION, $version);
		$v = sfSimpleBlogPostVersionPeer::doSelect($criteria, $con);

		return !empty($v) ? $v[0] : null;
	}
} // BasesfSimpleBlogPostVersionPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BasesfSimpleBlogPostVersionPeer::buildTableMap();

