<?php


/**
 * Base class that represents a query for the 'sf_blog_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed 26 Jan 2011 10:35:17 PM WIT
 *
 * @method     sfSimpleBlogCategoryQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     sfSimpleBlogCategoryQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method     sfSimpleBlogCategoryQuery orderByDescription($order = Criteria::ASC) Order by the description column
 *
 * @method     sfSimpleBlogCategoryQuery groupById() Group by the id column
 * @method     sfSimpleBlogCategoryQuery groupByName() Group by the name column
 * @method     sfSimpleBlogCategoryQuery groupByDescription() Group by the description column
 *
 * @method     sfSimpleBlogCategoryQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     sfSimpleBlogCategoryQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     sfSimpleBlogCategoryQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     sfSimpleBlogCategoryQuery leftJoinsfSimpleBlogPostCategory($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfSimpleBlogPostCategory relation
 * @method     sfSimpleBlogCategoryQuery rightJoinsfSimpleBlogPostCategory($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfSimpleBlogPostCategory relation
 * @method     sfSimpleBlogCategoryQuery innerJoinsfSimpleBlogPostCategory($relationAlias = null) Adds a INNER JOIN clause to the query using the sfSimpleBlogPostCategory relation
 *
 * @method     sfSimpleBlogCategory findOne(PropelPDO $con = null) Return the first sfSimpleBlogCategory matching the query
 * @method     sfSimpleBlogCategory findOneOrCreate(PropelPDO $con = null) Return the first sfSimpleBlogCategory matching the query, or a new sfSimpleBlogCategory object populated from the query conditions when no match is found
 *
 * @method     sfSimpleBlogCategory findOneById(int $id) Return the first sfSimpleBlogCategory filtered by the id column
 * @method     sfSimpleBlogCategory findOneByName(string $name) Return the first sfSimpleBlogCategory filtered by the name column
 * @method     sfSimpleBlogCategory findOneByDescription(string $description) Return the first sfSimpleBlogCategory filtered by the description column
 *
 * @method     array findById(int $id) Return sfSimpleBlogCategory objects filtered by the id column
 * @method     array findByName(string $name) Return sfSimpleBlogCategory objects filtered by the name column
 * @method     array findByDescription(string $description) Return sfSimpleBlogCategory objects filtered by the description column
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model.om
 */
abstract class BasesfSimpleBlogCategoryQuery extends ModelCriteria
{

	// query_cache behavior
	protected $queryKey = '';

	/**
	 * Initializes internal state of BasesfSimpleBlogCategoryQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'sfSimpleBlogCategory', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new sfSimpleBlogCategoryQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    sfSimpleBlogCategoryQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof sfSimpleBlogCategoryQuery) {
			return $criteria;
		}
		$query = new sfSimpleBlogCategoryQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    sfSimpleBlogCategory|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = sfSimpleBlogCategoryPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    sfSimpleBlogCategoryQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(sfSimpleBlogCategoryPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    sfSimpleBlogCategoryQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(sfSimpleBlogCategoryPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogCategoryQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(sfSimpleBlogCategoryPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the name column
	 * 
	 * @param     string $name The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogCategoryQuery The current query, for fluid interface
	 */
	public function filterByName($name = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($name)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $name)) {
				$name = str_replace('*', '%', $name);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogCategoryPeer::NAME, $name, $comparison);
	}

	/**
	 * Filter the query on the description column
	 * 
	 * @param     string $description The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogCategoryQuery The current query, for fluid interface
	 */
	public function filterByDescription($description = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($description)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $description)) {
				$description = str_replace('*', '%', $description);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(sfSimpleBlogCategoryPeer::DESCRIPTION, $description, $comparison);
	}

	/**
	 * Filter the query by a related sfSimpleBlogPostCategory object
	 *
	 * @param     sfSimpleBlogPostCategory $sfSimpleBlogPostCategory  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfSimpleBlogCategoryQuery The current query, for fluid interface
	 */
	public function filterBysfSimpleBlogPostCategory($sfSimpleBlogPostCategory, $comparison = null)
	{
		if ($sfSimpleBlogPostCategory instanceof sfSimpleBlogPostCategory) {
			return $this
				->addUsingAlias(sfSimpleBlogCategoryPeer::ID, $sfSimpleBlogPostCategory->getCategoryId(), $comparison);
		} elseif ($sfSimpleBlogPostCategory instanceof PropelCollection) {
			return $this
				->usesfSimpleBlogPostCategoryQuery()
					->filterByPrimaryKeys($sfSimpleBlogPostCategory->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterBysfSimpleBlogPostCategory() only accepts arguments of type sfSimpleBlogPostCategory or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the sfSimpleBlogPostCategory relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfSimpleBlogCategoryQuery The current query, for fluid interface
	 */
	public function joinsfSimpleBlogPostCategory($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfSimpleBlogPostCategory');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfSimpleBlogPostCategory');
		}
		
		return $this;
	}

	/**
	 * Use the sfSimpleBlogPostCategory relation sfSimpleBlogPostCategory object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfSimpleBlogPostCategoryQuery A secondary query class using the current class as primary query
	 */
	public function usesfSimpleBlogPostCategoryQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfSimpleBlogPostCategory($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfSimpleBlogPostCategory', 'sfSimpleBlogPostCategoryQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     sfSimpleBlogCategory $sfSimpleBlogCategory Object to remove from the list of results
	 *
	 * @return    sfSimpleBlogCategoryQuery The current query, for fluid interface
	 */
	public function prune($sfSimpleBlogCategory = null)
	{
		if ($sfSimpleBlogCategory) {
			$this->addUsingAlias(sfSimpleBlogCategoryPeer::ID, $sfSimpleBlogCategory->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

	// query_cache behavior
	
	public function setQueryKey($key)
	{
		$this->queryKey = $key;
		return $this;
	}
	
	public function getQueryKey()
	{
		return $this->queryKey;
	}
	
	public function cacheContains($key)
	{
		return apc_fetch($key);
	}
	
	public function cacheFetch($key)
	{
		return apc_fetch($key);
	}
	
	public function cacheStore($key, $value, $lifetime = 3600)
	{
		apc_store($key, $value, $lifetime);
	}
	
	protected function getSelectStatement($con = null)
	{
		$dbMap = Propel::getDatabaseMap(sfSimpleBlogCategoryPeer::DATABASE_NAME);
		$db = Propel::getDB(sfSimpleBlogCategoryPeer::DATABASE_NAME);
	  if ($con === null) {
			$con = Propel::getConnection(sfSimpleBlogCategoryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		
		if (!$this->hasSelectClause()) {
			$this->addSelfSelectColumns();
		}
	
	  $this->configureSelectColumns();
	  
		$con->beginTransaction();
		try {
			$this->basePreSelect($con);
			$key = $this->getQueryKey();
			if ($key && $this->cacheContains($key)) {
				$params = $this->getParams();
				$sql = $this->cacheFetch($key);
			} else {
				$params = array();
				$sql = BasePeer::createSelectSql($this, $params);
				if ($key) {
					$this->cacheStore($key, $sql);
				}
			}
			$stmt = $con->prepare($sql);
			$db->bindValues($stmt, $params, $dbMap);
			$stmt->execute();
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
		
		return $stmt;
	}
	
	protected function getCountStatement($con = null)
	{
		$dbMap = Propel::getDatabaseMap($this->getDbName());
		$db = Propel::getDB($this->getDbName());
	  if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
	
		$con->beginTransaction();
		try {
			$this->basePreSelect($con);
			$key = $this->getQueryKey();
			if ($key && $this->cacheContains($key)) {
				$params = $this->getParams();
				$sql = $this->cacheFetch($key);
			} else {
				if (!$this->hasSelectClause() && !$this->getPrimaryCriteria()) {
					$this->addSelfSelectColumns();
				}
				$params = array();
				$needsComplexCount = $this->getGroupByColumns()
					|| $this->getOffset()
					|| $this->getLimit()
					|| $this->getHaving()
					|| in_array(Criteria::DISTINCT, $this->getSelectModifiers());
				if ($needsComplexCount) {
					if (BasePeer::needsSelectAliases($this)) {
						if ($this->getHaving()) {
							throw new PropelException('Propel cannot create a COUNT query when using HAVING and  duplicate column names in the SELECT part');
						}
						$db->turnSelectColumnsToAliases($this);
					}
					$selectSql = BasePeer::createSelectSql($this, $params);
					$sql = 'SELECT COUNT(*) FROM (' . $selectSql . ') propelmatch4cnt';
				} else {
					// Replace SELECT columns with COUNT(*)
					$this->clearSelectColumns()->addSelectColumn('COUNT(*)');
					$sql = BasePeer::createSelectSql($this, $params);
				}
				if ($key) {
					$this->cacheStore($key, $sql);
				}
			}
			$stmt = $con->prepare($sql);
			$db->bindValues($stmt, $params, $dbMap);
			$stmt->execute();
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	
		return $stmt;
	}

} // BasesfSimpleBlogCategoryQuery
