<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_blog_about' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Fri 31 Dec 2010 05:30:18 AM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model
 */
class sfSimpleBlogAboutPeer extends BasesfSimpleBlogAboutPeer {

} // sfSimpleBlogAboutPeer
