<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_blog_post_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Sat 01 Jan 2011 04:51:19 PM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model
 */
class sfSimpleBlogPostCategoryPeer extends BasesfSimpleBlogPostCategoryPeer {

} // sfSimpleBlogPostCategoryPeer
