<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_blog_post_version' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Fri 14 Jan 2011 07:01:53 PM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model
 */
class sfSimpleBlogPostVersionQuery extends BasesfSimpleBlogPostVersionQuery {

} // sfSimpleBlogPostVersionQuery
