<?php



/**
 * Skeleton subclass for representing a row from the 'sf_blog_link' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Sat 14 May 2011 08:23:57 AM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model
 */
class sfSimpleBlogLink extends BasesfSimpleBlogLink {

} // sfSimpleBlogLink
