<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_blog_author' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Mon 10 Jan 2011 01:02:51 AM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model
 */
class sfSimpleBlogAuthorQuery extends PluginsfSimpleBlogAuthorQuery {

} // sfSimpleBlogAuthorQuery
