<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_blog_page' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Fri 08 Apr 2011 01:26:50 AM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model
 */
class sfSimpleBlogPagePeer extends BasesfSimpleBlogPagePeer {

} // sfSimpleBlogPagePeer
