<?php



/**
 * Skeleton subclass for representing a row from the 'sf_blog_archive' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Tue 07 Jun 2011 12:32:55 AM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model
 */
class sfSimpleBlogArchive extends PluginsfSimpleBlogArchive {

} // sfSimpleBlogArchive
