<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_blog_post' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Mon 27 Dec 2010 07:15:57 PM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model.plugin
 */
class PluginsfSimpleBlogPostPeer extends BasesfSimpleBlogPostPeer {

} // sfSimpleBlogPostPeer
