<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_blog_post' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Mon 27 Dec 2010 07:15:57 PM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfSimpleBlog15Plugin.lib.model.plugin
 */
class PluginsfSimpleBlogPostQuery extends BasesfSimpleBlogPostQuery {
  public function recent()
  {
    return $this->orderByInternalPublishedAt(Criteria::DESC);
  }

  public function published()
  {
    return $this->filterByIsPublished(true);
  }

  public function draft()
  {
    return $this->filterByIsPublished(false);
  }

  public function previousPublished($publishedAt)
  {
    return $this
      ->filterByInternalPublishedAt($publishedAt, Criteria::LESS_THAN)
      ->recent()
      ->published();
  }

  public function nextPublished($publishedAt)
  {
    return $this
      ->filterByInternalPublishedAt($publishedAt, Criteria::GREATER_THAN)
      ->orderByInternalPublishedAt('asc')
      ->published();
  }

  public function findByStrippedTitleAndDate($text, $date)
  {
    $this->filterByStrippedTitle($text);
    if (sfConfig::get('app_sfSimpleBlog_use_date_in_url', false))
    {
      $this->filterByPublishedAt($date);
    }
    return $this->findOne();
  }

  public function categorized($category)
  {
    return $this
       >join('sfSimpleBlogPost.sfSimpleBlogPostCategory')
      ->join('sfSimpleBlogPostCategory.sfSimpleBlogCategory')
      ->where('sfSimpleBlogCategory.Name = ?', $category);
  }

  public function tagged($tags = array())
  {
    $taggings = TagPeer::getTaggings($tags, array('model' => 'sfSimpleBlogPost'));
    return $this->filterById($taggings['sfSimpleBlogPost']);
  }
} // sfSimpleBlogPostQuery
