generator:
  class: sfPropelGenerator
  param:
    model_class:           sfSimpleBlogLinkCategory
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_simple_blog_link_category
    with_propel_route:     1
    
    config:
      actions: ~
      fields:  ~
      list:
        title: Link Categories
        display: [=name, description]
        max_per_page: 10
      filter:
        class: false
      form:    ~
      edit:
        title: Edit Link Category "%%name%%"
      new:
        title: New Link Category
